#!/bin/bash
if [[ "$#" -lt 1 ]]; then
	echo "must provide name of app"
	exit 1
fi

pythonInterpreter=python
command -v python
if [[ "$?" -ne 0 ]];then
    pythonInterpreter=python3
fi

$pythonInterpreter manage.py startapp $1

echo "success! Next steps are:"
echo "\tAdd to app's AppConfig to INSTALLED_APPS in settings"
echo "\tRegister models in admin portal if appropriate"
echo "\tGet cracking on the apps urls!"
