#!/bin/bash
pythonInterpreter=python
command -v python
if [[ "$?" -ne 0 ]];then
    pythonInterpreter=python3
fi
if [ "$#" -lt 1 ]; then
	echo "provide app to make migrations on"
	exit 1
fi
$pythonInterpreter manage.py makemigrations "$1"
