#!/bin/bash
pythonInterpreter=python
command -v python
if [[ "$?" -ne 0 ]];then
    pythonInterpreter=python3
fi

if [[ "$1" == "--cover" ]];then
    cover=true
fi

echo ""
echo "---------------------------------------------------------------------"
echo "= = = = = = = = = = lelantos_base Models  = = = = = = = = = = = = = = "
if [[ "$cover" == "true" ]];then
    coverage run --source=lelantos_base manage.py test -v 0 lelantos_base.tests
    coverage report --omit lelantos_base/management/*,lelantos_base/migrations/*
else
    $pythonInterpreter manage.py test -v 0 lelantos_base.tests
fi

echo ""
echo "---------------------------------------------------------------------"
echo "= = = = = = = = = = = = = Analysis  = = = = = = = = = = = = = = = = = "
if [[ "$cover" == "true" ]];then
    coverage run --source=analysis manage.py test -v 0 analysis.tests 
    coverage report --omit analysis/migrations/*,
else
    $pythonInterpreter manage.py test -v 0 analysis.tests
fi
