#!/bin/bash

# create json
python manage.py graph_models -a --json -o myapp_models.json

# Convert to xml
python ./ConvertGraphToXMLForDrawIO/convertGraphModelJsonToDrawIO.py --graph_models_json ./myapp_models.json --attemptFKRelations --nameMappingsJsonPath ./helpers/drawioModelMappings.json --output ./drawioXML.xml

# rm json
rm myapp_models.json