#!/bin/bash

pythonInterpreter=python
command -v python
if [[ "$?" -ne 0 ]];then
    pythonInterpreter=python3
fi

# create json
$pythonInterpreter manage.py graph_models -a --json -o myapp_models.json

# Convert to xml
$pythonInterpreter ./ConvertGraphToXMLForDrawIO/convertGraphModelJsonToDrawIO.py --graph_models_json ./myapp_models.json --attemptFKRelations --nameMappingsJsonPath ./helpers/drawioModelMappings.json --output ./drawioXML.xml

# rm json
rm myapp_models.json