#!/bin/bash
# move old database
mv dbWithGeo.sqlite3 dbWithGeo.sqlite3.old

# move old migrations
mkdir -p aircrack_ng_broker/migrations/_archive
mv aircrack_ng_broker/migrations/0*.py aircrack_ng_broker/migrations/_archive

mkdir -p wifiphisher_broker/migrations/_archive
mv wifiphisher_broker/migrations/0*.py wifiphisher_broker/migrations/_archive

mkdir -p wp3_basic/migrations/_archive
mv wp3_basic/migrations/0*.py wp3_basic/migrations/_archive

# Get python interpreter
pythonInterpreter=python
command -v python
if [[ "$?" -ne 0 ]];then
    pythonInterpreter=python3
fi
# make new migrations
$pythonInterpreter manage.py makemigrations
# prep for spatialite
$pythonInterpreter manage.py shell -c "import django;django.db.connection.cursor().execute('SELECT InitSpatialMetaData(1);')";
# migrate
$pythonInterpreter manage.py migrate

# mock data
$pythonInterpreter manage.py createMockData
