#!/bin/bash

addMockData="false"
if [[ "$#" == 1 ]]; then
    if [[ "$1" == "--addMockData" ]]; then
        addMockData="true"
    else
        echo "only optional parameter is --addMockData"
    fi
fi

# move old database
mv dbWithGeo.sqlite3 dbWithGeo.sqlite3.old

# move old migrations (order matters)
mkdir -p lelantos_base/migrations/_archive
mv lelantos_base/migrations/0*.py lelantos_base/migrations/_archive

mkdir -p aircrack_ng_broker/migrations/_archive
mv aircrack_ng_broker/migrations/0*.py aircrack_ng_broker/migrations/_archive

mkdir -p wifiphisher_broker/migrations/_archive
mv wifiphisher_broker/migrations/0*.py wifiphisher_broker/migrations/_archive

# Get python interpreter
pythonInterpreter=python
command -v python
if [[ "$?" -ne 0 ]];then
    pythonInterpreter=python3
fi
# make new migrations
$pythonInterpreter manage.py makemigrations lelantos_base
$pythonInterpreter manage.py makemigrations aircrack_ng_broker
$pythonInterpreter manage.py makemigrations wifiphisher_broker
# prep for spatialite
$pythonInterpreter manage.py shell -c "import django;django.db.connection.cursor().execute('SELECT InitSpatialMetaData(1);')";
# migrate
$pythonInterpreter manage.py migrate

# optional mock data
if [[ "$addMockData" == "true" ]];then
    $pythonInterpreter manage.py createMockData
fi
