#!/bin/bash
pythonInterpreter=python
command -v python
if [[ "$?" -ne 0 ]];then
    pythonInterpreter=python3
fi

# Prime database
./helpers/_resetDB

# create guest user (skips if already created)
./helpers/_createGuestUser

# start server
./helpers/_runServer