#!/bin/bash

# install geo-data extensions
sudo apt-get install -y binutils libproj-dev gdal-bin libgdal-dev g++
sudo apt-get install libsqlite3-mod-spatialite

# install python additionals
sudo apt-get install python3.12-venv python3-dev 

# Create and active virtual pytohn environment
python3 -m venv .lelantos-venv
source .lelantos-venv/bin/activate

# install requirements into environment
python3 -m pip install -r requirements.txt

# Prime database
./helpers/resetDB

# Run tests
./helpers/_test

# Create mock data
./helpers/_createMockData

# create guest user (skips if already created)
./helpers/_createGuestUser

# start server
./helpers/_runServer