# Generated by Django 5.0.1 on 2024-04-14 18:45

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('area', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Module_Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=2000)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('active', models.BooleanField()),
                ('pid', models.PositiveIntegerField(null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wp3_basic.location')),
            ],
        ),
        migrations.CreateModel(
            name='Device_Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_addr', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=200)),
                ('private_ip', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('first_seen', models.CharField(max_length=200)),
                ('module_session_captured', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wp3_basic.module_session')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Credential_Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('capture_time', models.CharField(max_length=200)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wp3_basic.device_instance')),
                ('module_session_captured', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wp3_basic.module_session')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('src_ip', models.CharField(max_length=15)),
                ('active', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='module_session',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wp3_basic.session'),
        ),
        migrations.AddField(
            model_name='location',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wp3_basic.session'),
        ),
        migrations.CreateModel(
            name='User_Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder', models.CharField(max_length=2000)),
                ('time_stamp', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wp3_basic.session')),
            ],
        ),
        migrations.CreateModel(
            name='Wp3_Authentication_Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=2000)),
                ('issued_at', models.DateTimeField()),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wp3_basic.session')),
            ],
        ),
    ]
