# Generated by Django 4.2.7 on 2023-11-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wp3_basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder', models.CharField(max_length=2000)),
                ('time_stamp', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='wp3_authentication_token',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Session_Authentication_Token',
        ),
    ]
