# Generated by Django 4.2.7 on 2023-11-04 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wp3_basic', '0002_user_action_session_wp3_authentication_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='wp3_authentication_token',
        ),
        migrations.AddField(
            model_name='session',
            name='src_ip',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Wp3_Authentication_Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=2000)),
                ('issued_at', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wp3_basic.session')),
            ],
        ),
    ]
