# Generated by Django 4.2.7 on 2023-11-04 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wp3_basic', '0003_remove_session_wp3_authentication_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('session_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('src_ip', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='wp3_authentication_token',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wp3_basic.activesession'),
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
