# Generated by Django 4.2.7 on 2023-11-04 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wp3_basic', '0004_activesession_alter_wp3_authentication_token_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_action',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wp3_basic.activesession'),
            preserve_default=False,
        ),
    ]
