# Generated by Django 4.2.7 on 2023-11-04 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wp3_basic', '0006_activesession_active_activesession_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('src_ip', models.CharField(max_length=15)),
                ('active', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='user_action',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wp3_basic.session'),
        ),
        migrations.AlterField(
            model_name='wp3_authentication_token',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wp3_basic.session'),
        ),
        migrations.DeleteModel(
            name='ActiveSession',
        ),
    ]
