# Generated by Django 4.2.7 on 2023-11-05 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wp3_basic', '0007_session_alter_user_action_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wp3_authentication_token',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wp3_basic.session'),
        ),
    ]
