# Generated by Django 4.2.7 on 2023-12-04 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wp3_basic', '0008_alter_wp3_authentication_token_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wp3_Rest_Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('active', models.BooleanField()),
                ('pid', models.PositiveIntegerField()),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wp3_basic.session')),
            ],
        ),
    ]
